
/**
 * the goal is to estimate the eletron mass from the compton spectra
 * of the following files:
 * gamma/plots/spettri_energia/Spettro_energia_ravvicinato_delay_ampl_0deg_Cs.pdf
 * gamma/plots/spettri_energia/Spettro_energia_trigger_mobile_0deg_Na.pdf
 * gamma/plots/spettri_energia/Spettro_energia_ravvicinato_delay_ampl_0deg_Co60.pdf
 * 
 * from the last one will be difficult since the compton is ruined by the second 
 * compton generated by the second photoelectric peak
*/

#include "TH1D.h"

/**
 * the data from the .mca are in mca channels, we calibrated the instrument to 
 * have data in energy eV. we estimate the conversion factor in poli_fit.cpp
*/

double p0 = -12.9527;
double p1 = 0.741858;
double p2 = 1.81343e-05;

void electron_mass() {

    gStyle->SetOptFit(1111);

    const char* file_Na = "../data/Spettro_energia_trigger_mobile_0deg_Na.mca";
    const char* file_Cs = "../data/Spettro_energia_ravvicinato_delay_ampl_0deg_Cs.mca";
    const char* file_Co = "../data/Spettro_energia_ravvicinato_delay_ampl_0deg_Co60.mca";

    int nchan = 2048;
    int nlines_start = 12;    
    int nlines_end = 2060;

    TH1D* hist_Na = new TH1D("hist_Na", "Na", nchan, 0, nchan);
    TH1D* hist_Cs = new TH1D("hist_Cs", "Cs", nchan, 0, nchan);
    TH1D* hist_Co = new TH1D("hist_Co", "Co", nchan, 0, nchan);

    FILE* f_Na = fopen(file_Na, "r");
    FILE* f_Cs = fopen(file_Cs, "r");
    FILE* f_Co = fopen(file_Co, "r");

    char line_Na[200], line_Cs[200], line_Co[200];
    int row_Na = 0, row_Cs = 0, row_Co = 0; 
    int ichan_Na = 0, ichan_Cs = 0, ichan_Co = 0;
    double y_Na = 0, y_Cs = 0, y_Co = 0;
    

    while (fgets(line_Na, 200, f_Na)) {

        if (row_Na >= nlines_start && row_Na < nlines_end) {
            if (sscanf(line_Na, "%lf", &y_Na) == 1) {
                hist_Na->AddBinContent(ichan_Na + 1, y_Na);
                ichan_Na++;
            }
        }

        if (row_Na >= nlines_end) break;
        row_Na++;
    }
    fclose(f_Na);
    
    while (fgets(line_Cs, 200, f_Cs)) {

        if (row_Cs >= nlines_start && row_Cs < nlines_end) {
            if (sscanf(line_Cs, "%lf", &y_Cs) == 1) {
                hist_Cs->AddBinContent(ichan_Cs + 1, y_Cs);
                ichan_Cs++;
            }
        }

        if (row_Cs >= nlines_end) break;
        row_Cs++;
    }
    fclose(f_Cs);

    while (fgets(line_Co, 200, f_Co)) {

        if (row_Co >= nlines_start && row_Co < nlines_end) {
            if (sscanf(line_Co, "%lf", &y_Co) == 1) {
                hist_Co->AddBinContent(ichan_Co + 1, y_Co);
                ichan_Co++;
            }
        }

        if (row_Co >= nlines_end) break;
        row_Co++;
    }
    fclose(f_Co);

    double x_bins[2049];
    for (int i = 0; i <= nchan; i++) {
        x_bins[i] = i * i * p2 + i * p1 + p0;
    }

    hist_Na->GetXaxis()->Set(nchan, x_bins);
    hist_Cs->GetXaxis()->Set(nchan, x_bins);
    hist_Co->GetXaxis()->Set(nchan, x_bins);

    TCanvas* cNa = new TCanvas("c1", "SpettroNa", 800, 600);
    TCanvas* cCs = new TCanvas("c2", "SpettroCs", 800, 600);
    TCanvas* cCo = new TCanvas("c3", "SpettroCo", 800, 600);


    //----------------------------Na22---------------------------------

    cNa->cd();
    double xmin_Na = 280.;
    double xmax_Na = 400.;
    TF1* sigmoid_Na = new TF1("sigmoid_Na", "([0] / (1.0 + exp((x - [1]) / [2]))) + [3]", xmin_Na, xmax_Na);
    sigmoid_Na->SetParameters(100., 328., 10., 10.);
    sigmoid_Na->SetParName(0, "N_{1}");
    sigmoid_Na->SetParName(1, "E_{edge} [keV]");
    sigmoid_Na->SetParName(2, "#sigma [keV]");
    sigmoid_Na->SetParName(3, "N_{2}");

    hist_Na->GetXaxis()->SetRangeUser(200., 450.);
    hist_Na->SetTitle("Spettro in coincidenza Na22");
    hist_Na->GetYaxis()->SetTitle("Conteggi");
    hist_Na->GetXaxis()->SetTitle("Energia [keV]");
    hist_Na->SetLineColor(kBlue+1);
    hist_Na->Fit(sigmoid_Na, "R");
    hist_Na->Draw("HIST");
    
    sigmoid_Na->SetLineWidth(3);
    sigmoid_Na->Draw("SAME");

    // evaluation of electron mass from compton in Na
    double E0_Na = 511.0; // keV
    double Eedge_Na = sigmoid_Na->GetParameter(1);
    double error_Eedge_Na = sigmoid_Na->GetParError(1); 

    // Calcolo della massa dell'elettrone
    double me_Na = ((2.0 * E0_Na * E0_Na) / (Eedge_Na)) - 2.0 * E0_Na;

    // --- PROPAGAZIONE DELL'ERRORE ---
    double derivata_Na = (2.0 * E0_Na * E0_Na) / (Eedge_Na * Eedge_Na);
    double error_me_Na = derivata_Na * error_Eedge_Na;
    // ---------------------------------

    printf("\n=========================================================\n");
    printf("Stima massa elettrone da Na: %lf +/- %lf [keV]\n", me_Na, error_me_Na);
    printf("=========================================================\n");

    //----------------------------Cs137--------------------------------

    cCs->cd();
    double xmin_Cs = 400.;
    double xmax_Cs = 550.;
    TF1* sigmoid_Cs = new TF1("sigmoid_Cs", "([0] / (1.0 + exp((x - [1]) / [2]))) + [3]", xmin_Cs, xmax_Cs);
    sigmoid_Cs->SetParameters(100., 450., 10., 10.);
    sigmoid_Cs->SetParName(0, "N_{1}");
    sigmoid_Cs->SetParName(1, "E_{edge} [keV]");
    sigmoid_Cs->SetParName(2, "#sigma [keV]");
    sigmoid_Cs->SetParName(3, "N_{2}");

    hist_Cs->GetXaxis()->SetRangeUser(300., 600.);
    hist_Cs->SetTitle("Spettro in coincidenza Cs137");
    hist_Cs->GetYaxis()->SetTitle("Conteggi");
    hist_Cs->GetXaxis()->SetTitle("Energia [keV]");
    hist_Cs->SetLineColor(kBlue+1);
    hist_Cs->Fit(sigmoid_Cs, "R");
    hist_Cs->Draw("HIST");

    sigmoid_Cs->SetLineWidth(3);
    sigmoid_Cs->Draw("SAME");

    // evaluation of electron mass from compton in Na
    double E0_Cs = 662.0; // keV
    double Eedge_Cs = sigmoid_Cs->GetParameter(1);
    double error_Eedge_Cs = sigmoid_Cs->GetParError(1); 

    // Calcolo della massa dell'elettrone
    double me_Cs = ((2.0 * E0_Cs * E0_Cs) / (Eedge_Cs)) - 2.0 * E0_Cs;

    // --- PROPAGAZIONE DELL'ERRORE ---
    double derivata_Cs = (2.0 * E0_Cs * E0_Cs) / (Eedge_Cs * Eedge_Cs);
    double error_me_Cs = derivata_Cs * error_Eedge_Cs;
    // ---------------------------------

    printf("\n=========================================================\n");
    printf("Stima massa elettrone da Cs: %lf +/- %lf [keV]\n", me_Cs, error_me_Cs);
    printf("=========================================================\n");

    
    //----------------------------Co60---------------------------------


    cCo->cd();
    hist_Co->SetTitle("Spettro in coincidenza Co60");
    hist_Co->GetYaxis()->SetTitle("Conteggi");
    hist_Co->GetXaxis()->SetTitle("Energia [keV]");
    hist_Co->SetLineColor(kBlue+1);
    hist_Co->Draw("HIST");



}